elementary/tasks

- src/ListView.vala
- src/MainWindow.vala
- src/Widgets/ListRow.vala
* If possible, remove the list with handy keyboard shortcuts Delete or Ctrl + Backspace
* If not possible, Gdk.Beep!
* Afterwards, try to select another list if one exists
* If not, deal better with setting a null source in the view
> Add an action for deleting the selected list

- .github/workflows/main.yml
We'll come back to Houston CI later
> Add build to CI

- data/gschema.xml
- src/ListView.vala
- src/Widgets/ListSettingsPopover.vala
- src/Widgets/TaskRow.vala
> Add a switch to show/hide completed items

- src/MainWindow.vala
- src/Widgets/ListSettingsPopover.vala
Do not show disabled tasklists in the sidebar.
> Hide disabled sources (tasklists)

- src/Widgets/TaskRow.vala
This fixes #35.
How to replace multiple linebreaks with just one? I expect my solution does not under all cirumstances, but didn't found a regex function for string.replace.
> Add task description in tasklist

- data/TaskRow.css
- data/gresource.xml
- src/Widgets/TaskRow.vala
* Fix CSS styling
* Fix linting error
* Fix check alignment for default font size
* Add more margin between rows
* Add full date/time to tooltip
* Don't use deprecated methods
> Fix style provider and layout

- src/ListView.vala
- src/Widgets/TaskRow.vala
Show checkbox in color of list.
> Accentuate checkbox

- src/ListView.vala
- src/Widgets/TaskRow.vala
- src/Widgets/TaskSettingsPopover.vala
This pull requests adds the possibility to actually modify a task and get the changes saved into the backend by using libecal.
**EDIT:** Fixes #60.
**EDIT 2:** Fixes https://github.com/elementary/tasks/issues/45 as well.
> Persist task changes to ECal backend

- data/EditableLabel.css
- data/gresource.xml
- meson.build
- po/POTFILES
- src/ListView.vala
- src/Widgets/EditableLabel.vala
- src/Widgets/ListSettingsPopover.vala
And get rid of the title entry in the popover
> Make title label directly editable

- src/ListView.vala
This should be vertical since it shows a menu (same view) and not a dialog or a new view
> ListView: Use vertical more icon

- data/TaskRow.css
- src/Widgets/TaskRow.vala
> TaskRow: style past due tasks

- meson.build
- src/ListView.vala
- src/Widgets/TaskSettingsPopover.vala
> Add support for libecal-2.0

- src/ListView.vala
- src/Widgets/TaskRow.vala
This handles both mouse and keyboard events for us
> Replace keypress events with row_activated.connect

- src/ListView.vala
- src/Widgets/TaskRow.vala
Adds the functionality to delete a task. Fixes #77.
> Deleting a task

- src/Widgets/TaskRow.vala
> TaskRow: make it build with libical-2.0

- data/TaskRow.css
- src/ListView.vala
- src/Widgets/TaskRow.vala
> Checkboxes update their color

- meson.build
- src/Application.vala
- src/ListView.vala
- src/MainWindow.vala
- src/TaskModel.vala
- src/Widgets/TaskRow.vala
This draft attempts to fix #99 in order to allow more flexible querying possibilities to create views for retrieving tasks. Needed by #98.
> Using task model to detach UI from EDS

- src/ListView.vala
- src/TaskModel.vala
- src/Widgets/TaskRow.vala
- vapi/libecal-1.2.vapi
Avoid having all completed. This Pull Request attempts to fix #105
> Complete occurence only

- meson.build
- src/Application.vala
- src/ListView.vala
- src/MainWindow.vala
- src/TaskModel.vala
- src/Util.vala
- src/Widgets/ScheduledRow.vala
- src/Widgets/TaskRow.vala
Replaces #98, Fixes #46.
Contains only the changes necessary for Schedule List based upon latest master and the feedback provided in #98 by @danrabbit.
This PR should be way easier to review.
> Scheduled List

- src/ListView.vala
- src/TaskModel.vala
- src/Widgets/TaskRow.vala
Replaces #97. Fixes #114 and #92.
> Add a task

- meson.build
- src/TaskModel.vala
- src/Util.vala
- src/Widgets/TaskRow.vala
Since Tasks will arrive on Odin only, I guess there is no need to support libecal-1.2 any longer?
> Dropped support for libecal-1.2

- README.md
follow up for dropped support for libecal-1.2 (#130)
> Made sure README contains libecal-2.0

- src/ListView.vala
No longer necessary with Hdy.Window
> ListView: remove 3px bottom margin

- data/SourceRow.css
- src/Widgets/ScheduledRow.vala
- src/Widgets/SourceRow.vala
* Fix border color
* Use colored appointment icon in sidebar
* Match circle size
> Sidebar: misc style fixes

- .github/workflows/gettext.yml
So that we can get translation files updated automatically
> Add Gettext Updates to Actions

- src/TaskModel.vala
> Update task asynchronous

- src/Widgets/ListSettingsPopover.vala
To match https://github.com/elementary/switchboard-plug-pantheon-shell/pull/247
> ListSettingsPopover: Re-order accent colors

- src/ListView.vala
- src/MainWindow.vala
- src/Widgets/EditableLabel.vala
- src/Widgets/ListSettingsPopover.vala
- src/Widgets/ScheduledRow.vala
- src/Widgets/SourceRow.vala
- src/Widgets/TaskRow.vala
Doing some housekeeping. This PR ensures Objects are initialized with properties according to the docs:
https://docs.elementary.io/develop/writing-apps/code-style#initialize-objects-with-properites
> Code Style: Initialize Objects with Properites

- src/TaskModel.vala
> GTasks: Simplify task list rename

- src/Util.vala
Fixes #225 by using builtin utility functions for dealing with x properties.
> Using ECal util functions for custom properties

- .github/workflows/ci.yml
- io.elementary.tasks.yml
* Only run CI on PRs
* Update flatpak action
* Update lint to checkout v2
> CI: update flatpak action

- src/TaskModel.vala
fixing issue [240](https://github.com/elementary/tasks/issues/240)
> fixing uncheck error message

- src/MainWindow.vala
Wanna try to sneak this in before release :)
> MainWindow: Add link to Online Accounts

- src/MainWindow.vala
> Automatically position window controls with Hdy.HeaderGroup

- .github/workflows/ci.yml
- .github/workflows/merge.yml
- .github/workflows/release.yml
Needs branch protection rules updated if approved
> Add aarch64 architecture support to flatpak builds

- src/MainWindow.vala
> Expand items in add list popover

- data/icons/128.svg
- data/icons/16.svg
- data/icons/24.svg
- data/icons/32.svg
- data/icons/48.svg
- data/icons/64.svg
Playing with the idea of a square icon where an element breaks out of the square
> Square icon design

- debian/control
> Add libportal dependency

- src/Application.vala
> Fix `notify` Signature in `prefers-color-scheme` Callback

- data/gschema.xml
- src/Application.vala
- src/MainWindow.vala
GTK 4/Wayland prep. Can't set window position in Wayland
> gschema: remove window position

- src/Widgets/TaskListGrid.vala
* Code style
* Dialog present/response
* Child property
* no more Widget.get_action_group so get window
* Can't Widget.get_children so use get_row_at_index to remove all
> TaskListGrid: Gtk4 prep

- src/Widgets/ListSettingsPopover.vala
- src/Widgets/TaskListGrid.vala
* Set source when instantiating
* set `group` on Radios since there's no `from_widget` in GTK4
* Use child property
* use dialog `present` and connect to response
> ListSettingsPopover: GTK4 prep

- src/Widgets/EntryPopover/Location.vala
No more Granite.ModeButton in GTK4, so use Gtk.RadioButtons in a .linked box
> Location: Granite.ModeButton → Gtk.RadioButton

- meson.build
- src/MainWindow.vala
- src/Widgets/ScheduledTaskListBox.vala
- src/Widgets/TaskListGrid.vala
Save some space. Get shadow when scrolled
> TaskListGrid: use ToolbarView

- meson.build
- po/POTFILES
- src/MainWindow.vala
- src/Views/ListView.vala
- src/Views/ScheduledView.vala
Hopefully make the code easier to navigate. I was confused for a second trying to find the files for the views
> Move Schedule and List views to Views folder

- .github/workflows/ci.yml
- .github/workflows/release.yml
The branch still exists but seems to be behind from the main
> Actions: Use main branch
