src/ListView.vala
This fixes #41: Seems if we pass in an empty query string, all tasks are loaded. @danrabbit can you confirm?
=> Load all tasks

src/Widgets/TaskRow.vala
To make them easier to distinguish from the ones which are incomplete in a list where items of both states are shown.
=> Use a lighter tone for the completed label summary text.

src/Widgets/TaskRow.vala
Fixed a typo which stripped the description line twice.
=> Fixed stripped_line typo to avoid doing same work twice

data/TaskRow.css, src/Widgets/TaskRow.vala
=> Output due date where it is set

src/Widgets/TaskSettingsPopover.vala
Fixes a visual issue with the popover arrow:
=> TaskSettingsPopover: Add a frame and margins around description

data/TaskRow.css, src/Widgets/TaskRow.vala
Instead of using EditableLabel, we use a flat entry.
This makes it so when we're editing that label we're editing the task. Also make sure keyboard events match up.
Manually listening to entry activation should eventually be replaced with `activates_default`, but we can't do that while buttons are in another class so it'll have to wait
=> TaskRow: Don't use editable label

data/TaskRow.css
=> TaskRow: Add margin to card bottom

src/Widgets/TaskRow.vala
For whatever reason after compiling the new master branch PR #116 no longer worked. This PR fixes the problem.
=> Fix for calcomponent-created in libecal 1

src/Application.vala
This makes each source's color be used again in the big header of the main view.
=> Restore Header Coloring

src/MainWindow.vala
This fixes restoring the last selected task list. We must connect to the select_row before making the selection. Otherwise the first selection is missed
=> MainWindow: Connect select_row before selection

data/TaskRow.css, src/Widgets/TaskRow.vala
Save the style context so we don't get it every time we hide/show task details
Use Granite rounded style class instead of hard coding card radius
=> TaskRow: Save style context and use Rounded

po/meson.build, src/Widgets/TaskRow.vala
It would be difficult to understand the context of the string "%s at %s" without any comment for translators.
=> TaskRow: Add TRANSLATORS comment for due date and time

data/EntryPopover.css, data/gresource.xml, src/Widgets/DateTimePopover.vala, src/Widgets/EntryPopover.vala, src/Widgets/TaskRow.vala
Widget construction should happen in the construct block. We don't use this style of constructing widgets during property declaration anywhere else. As you can see here, doing it that way lead to a lot of things being scoped to the whole class that are only accessed during construct.
We can also use property bindings to make our property setters simpler and can do a one line getter with `{ get; private set; }`
There were a number of extra properties here. `always_show_image` only needs to be set if the button also contains text. `use_popover` only applies if you're construction a menu button from a model.
You should use `-symbolic` icon names for flat styled icons so that they pick up the text color. This is especially important for dark mode.
Speaking of text color, there appears to be a …
=> Code style and CSS fixes

src/Widgets/TaskRow.vala
The ICal.Component might exist but not the created time.
=> TaskRow: Prevent the use of NULL ICal.Time object

meson.build, src/TaskModel.vala
And provide backwards compatibility to the shipped eds version in the Ubuntu 20.04 LTS as well.
=> Fix compile errors in EDS v3.39.2+

src/ListView.vala, src/Widgets/TaskRow.vala
This PR lays the foundation to implement drag & drop of tasks (#168). That means, we avoid `grab_focus` and rely on list selection functionality provided by ListBox to expand/collapse a TaskRow.
=> Use row_activated instead of focus to allow future drag and drop

src/Widgets/ListView.vala
This PR fixes https://github.com/elementary/tasks/issues/228. Turned out we just need to make sure to sort using due date when on Scheduled List (that is: no specific source is set for the list view).
**Before**
**After**
=> Fix Scheduled List sort

io.elementary.tasks.yml
Fixes #262 
I don't know which library we're using here that is trying to initialize an OpenGL context when it starts up (champlain maybe), but it's causing the application to crash on start with devices using the proprietary nvidia driver.
We should add this permission in by default.
=> flatpak manifest: Add DRI permission

data/tasks.appdata.xml.in, src/Widgets/TaskListGrid.vala
Fixes a crash experienced by users with a lot of tasks per list (https://github.com/elementary/tasks/issues/294). The root cause there is, that we are loading all tasks per default - even the completed ones.
This PR mitigates the situation by only loading the non-completed tasks by default. If the user enables "Show Completed", then a new query is executed which also retrieves the completed tasks.
Please note, loading the completed tasks as well would still lead to the crash. But in Gtk3 there is no builtin way to mitigate this, because Gtk.ListBox simply renders whatever we throw at it - instead of only doing so for the visible area only. A more elegant fix would be to use [Gtk4's ListView](https://valadoc.org/gtk4/Gtk.ListView.html) - but at the time of writing this is not possible, …
=> Load only non-completed tasks by default

data/tasks.appdata.xml.in, src/Widgets/TaskRow.vala
During my HyperTextView testings I noticed the cursor placing in the description text view does not behave as expected on focus. This PR fixes this.
**Without this PR**
https://user-images.githubusercontent.com/392542/132178799-8fba8b44-2a44-4cc9-83ac-f36bcaafb309.mp4
**With this PR**
https://user-images.githubusercontent.com/392542/132178429-2496e6bc-d0a6-4133-b126-96c9e6c39691.mp4
=> Fix cursor placing on focus

data/tasks.appdata.xml.in, src/Application.vala
This PR does some refactoring to make lifecycle management of the main_window easier. This allows us to get rid of an additional instance variable and is based upon the findings of https://github.com/elementary/mail/issues/721
This PR also adds the missing changelog entry about the new Notifications in AppData.
=> Refactor: Use Gtk.Application.active_window

data/tasks.appdata.xml.in, src/MainWindow.vala, src/TaskModel.vala
This PR introduces an automatic way of keeping task lists current: Instead of just relaying on a regular sync interval we try to be a bit smarter and automatically synchronize a task list whenever it is selected by the user and a network connection is available - or if the network becomes available again.
This fixes https://github.com/elementary/tasks/issues/306 as it basically obsoletes an extra refresh button.
=> Auto refresh task lists and collections

.github/workflows/ci.yml, eds-gdatasession.patch, io.elementary.tasks.yml, meson.build, src/TaskModel.vala
Also update some dependencies.
Fixes: #340
=> flatpak: Use 7.1 runtime

io.elementary.tasks.yml
Also always use archive type to speedup subsequent builds with flatpak-builder.
=> flatpak: Update the dependencies

src/MainWindow.vala
Fix a small color issue that was noticeable using dark mode (see red arrow in the screenshot) by adding `Gtk.STYLE_CLASS_BACKGROUND` to `main_grid`.
Before:
After:
=> Fix a small color issue

src/Widgets/ScheduledTaskListBox.vala
Fixes #359
I tried fix it issue https://github.com/elementary/tasks/issues/359
I think found solution if change get_children () to task_list.get_children () it method can remove repeated items
=> Fixed Duplicated tasks in Scheduled

debian/postinst
Fixes #369 
Tested locally and it actually removes the file.
=> Remove old autostart file

.github/workflows/merge.yml
We're using 7.1 in the PR CI so bumped that here too
=> CI: Use flatpak gettext action

.github/workflows/ci.yml
Since we're not currently shipping the Flatpak, make sure we're actually building against the OS
=> CI: build against OS

data/Application.css, src/Widgets/TaskRow.vala
* Use child property
* Replace ButtonBox
* Code style
* TextView border is replaced with margin
* KeyController
=> TaskRow: GTK4 Prep

src/MainWindow.vala, src/TaskModel.vala, src/Widgets/TaskListGrid.vala
Pulls out a lot of the changes to unowned refs from #358 and adds a couple more
Could be rebase merged if desired
=> Change references to unowned

src/Widgets/EditableLabel.vala
* Use Event Controllers
* We already have a good hover indicator for an editable item: the cursor. Remove the button revealer and use cursor
* Code style
* `grab_focus` isn't a signal in GTK 4
=> EditableLabel: Gtk4 Prep

src/Widgets/EntryPopover/Generic.vala
* Use motion controller
* Construct button contents in GTK4 friendly way
* Code style
* use child property
=> EntryPopover/Generic: Gtk4 Prep

meson.build, src/MainWindow.vala, src/Widgets/EntryPopover/DateTime.vala, src/Widgets/ListSettingsPopover.vala, src/Widgets/PopoverMenuitem.vala
Gtk.ModelButton is private in Gtk4
=> Add PopoverMenuitem

src/Widgets/ScheduledTaskListBox.vala
* Can't `get_children` so iterate by index instead
* `remove` instead of `destroy`
* Minor code style with namespaced constants
* use `child` property
* Can't get action group by name, so instead lookup action from the main window
* Can't set ellipsize on HeaderLabel since it's no longer a label subclass
* Remove unnecessary idles (review with hide whitespace changes)
* use dialog `present` and connect to `response` since we can't `run`
=> ScheduledTaskListBox: GTK4 prep
